name: Run Tests Before Push to Master

on:
  push:
    branches:
      - master  # Trigger when there's a push to the master branch

jobs:
  run-tests:
    runs-on: self-hosted  # Use the self-hosted runner
    
    strategy:
      matrix:
        test-library: ['jest', 'mocha', 'vitest', 'jasmine']  # Matrix to run tests for each library

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install  # Install root dependencies first (if any)

      - name: Install dependencies for Jest
        if: matrix.test-library == 'jest'
        run: |
          cd HelloJest  # Navigate to the HelloJest directory
          npm install   # Install Jest-specific dependencies (if defined)

      - name: Install dependencies for Mocha
        if: matrix.test-library == 'mocha'
        run: |
          cd HelloMocha  # Navigate to the HelloMocha directory
          npm install    # Install Mocha-specific dependencies (if defined)

      - name: Install dependencies for Vitest
        if: matrix.test-library == 'vitest'
        run: |
          cd HelloVitest  # Navigate to the HelloVitest directory
          npm install     # Install Vitest-specific dependencies (if defined)

      - name: Install dependencies for Jasmine
        if: matrix.test-library == 'jasmine'
        run: |
          cd HelloJasmine  # Navigate to the HelloJasmine directory
          npm install      # Install Jasmine-specific dependencies (if defined)

      - name: Run Jest tests
        if: matrix.test-library == 'jest'
        run: |
          cd HelloJest  # Navigate to the HelloJest directory
          npm run test   # Run Jest tests

      - name: Run Mocha tests
        if: matrix.test-library == 'mocha'
        run: |
          cd HelloMocha  # Navigate to the HelloMocha directory
          npm run test   # Run Mocha tests

      - name: Run Vitest tests
        if: matrix.test-library == 'vitest'
        run: |
          cd HelloVitest  # Navigate to the HelloVitest directory
          npm run test    # Run Vitest tests

      - name: Run Jasmine tests
        if: matrix.test-library == 'jasmine'
        run: |
          cd HelloJasmine  # Navigate to the HelloJasmine directory
          npm run test      # Run Jasmine tests
