name: Run Tests Before Push to Master

on:
  push:
    branches:
      - master  # Triggers when there’s a push to the master branch

jobs:
  run-tests:
    runs-on: self-hosted  # Use self-hosted runner
    
    strategy:
      matrix:
        test-library: ['jest', 'jasmine', 'test-library-3', 'test-library-4']  # Add your test libraries here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest tests
        if: matrix.test-library == 'jest'
        run: |
          cd jest-project  # Navigate to your Jest project directory
          npm run test     # Run Jest tests

      - name: Run Jasmine tests
        if: matrix.test-library == 'jasmine'
        run: |
          cd jasmine-project  # Navigate to your Jasmine project directory
          npm run test         # Run Jasmine tests

      - name: Run tests for Test Library 3
        if: matrix.test-library == 'test-library-3'
        run: |
          cd test-library-3  # Navigate to your third test project directory
          npm run test        # Run the tests for the third library

      - name: Run tests for Test Library 4
        if: matrix.test-library == 'test-library-4'
        run: |
          cd test-library-4  # Navigate to your fourth test project directory
          npm run test        # Run the tests for the fourth library
